#!/usr/bin/env python3
"""
Pull Settlement Reports from SP-API

Settlement reports are auto-generated by Amazon every ~2 weeks.
Pattern: LIST available reports → DOWNLOAD each one (not create-poll-download).

Each settlement report contains per-order transaction-level fee breakdowns:
- Referral fees (Commission)
- FBA fulfillment fees
- Refunds
- Promotions/Coupons
- Shipping income
- Other fees

This is the PRIMARY data source for accurate CM2 calculation.

Usage:
    python pull_settlements.py                          # New reports since last pull
    python pull_settlements.py --since 2026-01-01       # Reports since date
    python pull_settlements.py --marketplace USA        # Single marketplace
    python pull_settlements.py --dry-run                # Test without DB writes

Environment Variables Required:
    SP_LWA_CLIENT_ID      - Login With Amazon Client ID
    SP_LWA_CLIENT_SECRET  - Login With Amazon Client Secret
    SP_REFRESH_TOKEN_NA   - North America refresh token
    SUPABASE_URL          - Supabase project URL
    SUPABASE_SERVICE_KEY  - Supabase service role key
"""

import os
import sys
import argparse
import time
from datetime import date, datetime, timedelta
from typing import Dict, List, Any, Optional

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.auth import get_access_token
from utils.financial_reports import (
    list_settlement_reports,
    download_settlement_report,
    parse_settlement_rows,
    FINANCIAL_REPORT_TYPES
)
from utils.inventory_reports import MARKETPLACE_IDS
from utils.db import (
    get_supabase_client,
    create_data_import,
    update_data_import,
    create_financial_pull_record,
    update_financial_pull_status,
    get_processed_settlement_ids,
    upsert_settlement_transactions,
    upsert_settlement_summary,
    MARKETPLACE_UUIDS,
)

# Default marketplaces to pull
DEFAULT_MARKETPLACES = ["USA", "CA", "MX"]

# Rate limit between report downloads (seconds)
DOWNLOAD_DELAY = 10  # Increased from 5s - was getting 429s with 11 reports


def get_default_since_date() -> str:
    """
    Default: last 30 days for weekly pulls.
    Settlement reports are generated every ~2 weeks, so 30 days
    covers at least 1-2 new reports.
    """
    since = date.today() - timedelta(days=30)
    return since.strftime("%Y-%m-%dT00:00:00Z")


def pull_marketplace_settlements(
    access_token: str,
    marketplace_code: str,
    since_date: str,
    region: str = "NA",
    dry_run: bool = False,
    max_reports: int = 100
) -> Dict[str, Any]:
    """
    Pull all new settlement reports for a marketplace.

    Args:
        access_token: Valid SP-API access token
        marketplace_code: Marketplace code (e.g., 'USA')
        since_date: ISO date string to list reports from
        region: API region
        dry_run: If True, don't write to database
        max_reports: Maximum number of reports to process

    Returns:
        Dict with pull statistics
    """
    start_time = time.time()
    report_type = FINANCIAL_REPORT_TYPES["SETTLEMENT"]
    marketplace_id = MARKETPLACE_UUIDS[marketplace_code]

    print(f"\n{'='*60}")
    print(f"Settlement Reports for {marketplace_code}")
    print(f"Since: {since_date}")
    print(f"{'='*60}")

    # Step 1: List available settlement reports
    try:
        reports = list_settlement_reports(
            access_token, marketplace_code, region, since_date, max_reports
        )
    except Exception as e:
        print(f"  ✗ Error listing reports: {e}")
        return {
            "status": "failed",
            "marketplace": marketplace_code,
            "error": str(e),
            "reports_processed": 0,
            "total_transactions": 0
        }

    if not reports:
        print(f"  No new settlement reports found")
        return {
            "status": "no_data",
            "marketplace": marketplace_code,
            "reports_processed": 0,
            "total_transactions": 0
        }

    # Step 2: Check which settlement IDs we've already processed
    if not dry_run:
        processed_ids = get_processed_settlement_ids(marketplace_code)
        processed_set = set(processed_ids)
        print(f"  Already processed: {len(processed_set)} settlement reports")
    else:
        processed_set = set()

    # Step 3: Process each report
    reports_processed = 0
    reports_skipped = 0
    total_transactions = 0
    errors = []

    for i, report in enumerate(reports):
        report_id = report.get("reportId", "")
        report_doc_id = report.get("reportDocumentId", "")
        created_time = report.get("createdTime", "")

        print(f"\n  Report {i+1}/{len(reports)}: {report_id}")
        print(f"    Created: {created_time}")
        print(f"    Document: {report_doc_id}")

        if not report_doc_id:
            print(f"    ⚠️  No reportDocumentId — skipping")
            continue

        # Download and peek at settlement ID before deciding to skip
        try:
            # Rate limit between downloads
            if i > 0:
                print(f"    Waiting {DOWNLOAD_DELAY}s (rate limit)...")
                time.sleep(DOWNLOAD_DELAY)

            # Download report
            rows = download_settlement_report(access_token, report_doc_id, region)
            print(f"    Downloaded: {len(rows)} rows")

            if not rows:
                print(f"    ⚠️  Empty report — skipping")
                continue

            # Get settlement ID from first row
            settlement_id = rows[0].get("settlement-id", "").strip()
            if not settlement_id:
                print(f"    ⚠️  No settlement ID in data — skipping")
                continue

            print(f"    Settlement ID: {settlement_id}")

            # Check if already processed
            if settlement_id in processed_set:
                print(f"    ⏭️  Already processed — skipping")
                reports_skipped += 1
                continue

            if dry_run:
                # Parse but don't save
                transactions, summary = parse_settlement_rows(
                    rows, marketplace_id
                )
                print(f"    [DRY RUN] Would upsert {len(transactions)} transactions")
                if summary:
                    print(f"    [DRY RUN] Settlement period: "
                          f"{summary.get('settlement_start_date', '?')} to "
                          f"{summary.get('settlement_end_date', '?')}")
                    print(f"    [DRY RUN] Total amount: "
                          f"{summary.get('total_amount', '?')} "
                          f"{summary.get('currency_code', '?')}")
                total_transactions += len(transactions)
                reports_processed += 1
                continue

            # Create tracking records
            import_id = create_data_import(
                marketplace_code,
                date.today(),
                import_type="sp_api_settlement"
            )

            pull_id = create_financial_pull_record(
                marketplace_code=marketplace_code,
                report_type=report_type,
                pull_date=date.today(),
                import_id=import_id,
                settlement_id=settlement_id,
                report_id=report_id,
                report_document_id=report_doc_id
            )

            # Parse rows
            transactions, summary = parse_settlement_rows(
                rows, marketplace_id, import_id
            )

            # Upsert transactions
            tx_count = upsert_settlement_transactions(transactions)
            print(f"    ✅ Upserted {tx_count} transactions")

            # Upsert summary
            if summary:
                upsert_settlement_summary(summary)
                print(f"    ✅ Settlement summary saved"
                      f" ({summary.get('settlement_start_date', '?')} to "
                      f"{summary.get('settlement_end_date', '?')})")

            # Update tracking
            processing_time = int((time.time() - start_time) * 1000)
            update_financial_pull_status(
                pull_id, "completed",
                row_count=tx_count,
                processing_time_ms=processing_time
            )
            update_data_import(
                import_id, "completed",
                row_count=tx_count,
                processing_time_ms=processing_time
            )

            total_transactions += tx_count
            reports_processed += 1
            processed_set.add(settlement_id)

        except Exception as e:
            error_msg = str(e)
            print(f"    ✗ Error: {error_msg}")
            errors.append({"report_id": report_id, "error": error_msg})

            if not dry_run and 'pull_id' in dir() and pull_id:
                update_financial_pull_status(pull_id, "failed", error_message=error_msg)
            if not dry_run and 'import_id' in dir() and import_id:
                update_data_import(import_id, "failed", error_message=error_msg)

    # Summary
    processing_time = int((time.time() - start_time) * 1000)

    result = {
        "status": "completed" if not errors else "partial",
        "marketplace": marketplace_code,
        "reports_found": len(reports),
        "reports_processed": reports_processed,
        "reports_skipped": reports_skipped,
        "total_transactions": total_transactions,
        "errors": len(errors),
        "processing_time_ms": processing_time
    }

    if dry_run:
        result["status"] = "dry_run"

    return result


def main():
    parser = argparse.ArgumentParser(
        description="Pull Settlement Reports from SP-API"
    )
    parser.add_argument(
        "--since",
        type=str,
        help="List reports created since this date (YYYY-MM-DD). Default: last 30 days."
    )
    parser.add_argument(
        "--marketplace",
        type=str,
        help="Specific marketplace to pull (e.g., USA, CA, MX)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Pull data but don't write to database"
    )
    parser.add_argument(
        "--max-reports",
        type=int,
        default=100,
        help="Maximum reports to process per marketplace (default: 100)"
    )

    args = parser.parse_args()

    # Determine since date
    if args.since:
        since_date = f"{args.since}T00:00:00Z" if "T" not in args.since else args.since
    else:
        since_date = get_default_since_date()

    # Determine marketplaces
    if args.marketplace:
        marketplaces = [args.marketplace.upper()]
    else:
        marketplaces = DEFAULT_MARKETPLACES

    # Validate marketplaces
    for mp in marketplaces:
        if mp not in MARKETPLACE_IDS:
            print(f"Error: Invalid marketplace '{mp}'")
            sys.exit(1)

    print("=" * 60)
    print("SETTLEMENT REPORT PULL")
    print(f"Since: {since_date}")
    print(f"Marketplaces: {', '.join(marketplaces)}")
    print(f"Max reports/marketplace: {args.max_reports}")
    print(f"Dry run: {args.dry_run}")
    print("=" * 60)

    # Get access token
    print("\nGetting access token...")
    access_token = get_access_token()
    print("✓ Access token obtained")

    # Process each marketplace
    results = []
    for i, marketplace in enumerate(marketplaces):
        if i > 0:
            # Rate limit between marketplace listing calls
            print("\nWaiting 5 seconds between marketplaces...")
            time.sleep(5)

        result = pull_marketplace_settlements(
            access_token,
            marketplace,
            since_date,
            region="NA",
            dry_run=args.dry_run,
            max_reports=args.max_reports
        )
        results.append(result)

    # Summary
    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)

    total_reports = 0
    total_transactions = 0
    failed = 0

    for result in results:
        marketplace = result["marketplace"]
        status = result["status"]

        if status in ["completed", "dry_run", "partial", "no_data"]:
            reports_processed = result.get("reports_processed", 0)
            transactions = result.get("total_transactions", 0)
            skipped = result.get("reports_skipped", 0)
            total_reports += reports_processed
            total_transactions += transactions

            status_icon = "✓" if status in ["completed", "dry_run"] else "⚠️"
            print(f"  {marketplace}: {status_icon} {reports_processed} reports, "
                  f"{transactions} transactions"
                  f"{f', {skipped} skipped' if skipped else ''}")
        else:
            failed += 1
            print(f"  {marketplace}: ✗ {result.get('error', 'Unknown error')}")

    print(f"\nTotal: {total_reports} reports, {total_transactions} transactions "
          f"from {len(marketplaces) - failed}/{len(marketplaces)} marketplaces")

    if failed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
